// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: currentStoreService.proto

package services

import (
	common "github.com/geiqin/micro-kit/protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreId string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id"`
}

func (x *CurrentStoreRequest) Reset() {
	*x = CurrentStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currentStoreService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentStoreRequest) ProtoMessage() {}

func (x *CurrentStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currentStoreService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentStoreRequest.ProtoReflect.Descriptor instead.
func (*CurrentStoreRequest) Descriptor() ([]byte, []int) {
	return file_currentStoreService_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentStoreRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type CurrentStoreData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store   *Store   `protobuf:"bytes,1,opt,name=store,proto3" json:"store"`
	Msg     string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg"`
	Modules []string `protobuf:"bytes,5,rep,name=Modules,proto3" json:"Modules"`
}

func (x *CurrentStoreData) Reset() {
	*x = CurrentStoreData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currentStoreService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentStoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentStoreData) ProtoMessage() {}

func (x *CurrentStoreData) ProtoReflect() protoreflect.Message {
	mi := &file_currentStoreService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentStoreData.ProtoReflect.Descriptor instead.
func (*CurrentStoreData) Descriptor() ([]byte, []int) {
	return file_currentStoreService_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentStoreData) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *CurrentStoreData) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CurrentStoreData) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type CurrentStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *CurrentStoreData `protobuf:"bytes,1,opt,name=data,proto3" json:"data"`
	Error *common.Error     `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
}

func (x *CurrentStoreResponse) Reset() {
	*x = CurrentStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_currentStoreService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentStoreResponse) ProtoMessage() {}

func (x *CurrentStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currentStoreService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentStoreResponse.ProtoReflect.Descriptor instead.
func (*CurrentStoreResponse) Descriptor() ([]byte, []int) {
	return file_currentStoreService_proto_rawDescGZIP(), []int{2}
}

func (x *CurrentStoreResponse) GetData() *CurrentStoreData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CurrentStoreResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_currentStoreService_proto protoreflect.FileDescriptor

var file_currentStoreService_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x13,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x22, 0x65,
	0x0a, 0x10, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x14, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x23, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xa9, 0x01, 0x0a, 0x13, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x04, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d,
	0x5a, 0x0b, 0x2f, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_currentStoreService_proto_rawDescOnce sync.Once
	file_currentStoreService_proto_rawDescData = file_currentStoreService_proto_rawDesc
)

func file_currentStoreService_proto_rawDescGZIP() []byte {
	file_currentStoreService_proto_rawDescOnce.Do(func() {
		file_currentStoreService_proto_rawDescData = protoimpl.X.CompressGZIP(file_currentStoreService_proto_rawDescData)
	})
	return file_currentStoreService_proto_rawDescData
}

var file_currentStoreService_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_currentStoreService_proto_goTypes = []interface{}{
	(*CurrentStoreRequest)(nil),  // 0: services.CurrentStoreRequest
	(*CurrentStoreData)(nil),     // 1: services.CurrentStoreData
	(*CurrentStoreResponse)(nil), // 2: services.CurrentStoreResponse
	(*Store)(nil),                // 3: services.Store
	(*common.Error)(nil),         // 4: common.Error
}
var file_currentStoreService_proto_depIdxs = []int32{
	3, // 0: services.CurrentStoreData.store:type_name -> services.Store
	1, // 1: services.CurrentStoreResponse.data:type_name -> services.CurrentStoreData
	4, // 2: services.CurrentStoreResponse.error:type_name -> common.Error
	0, // 3: services.CurrentStoreService.Info:input_type -> services.CurrentStoreRequest
	0, // 4: services.CurrentStoreService.Detail:input_type -> services.CurrentStoreRequest
	2, // 5: services.CurrentStoreService.Info:output_type -> services.CurrentStoreResponse
	2, // 6: services.CurrentStoreService.Detail:output_type -> services.CurrentStoreResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_currentStoreService_proto_init() }
func file_currentStoreService_proto_init() {
	if File_currentStoreService_proto != nil {
		return
	}
	file_storeService_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_currentStoreService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_currentStoreService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentStoreData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_currentStoreService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_currentStoreService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currentStoreService_proto_goTypes,
		DependencyIndexes: file_currentStoreService_proto_depIdxs,
		MessageInfos:      file_currentStoreService_proto_msgTypes,
	}.Build()
	File_currentStoreService_proto = out.File
	file_currentStoreService_proto_rawDesc = nil
	file_currentStoreService_proto_goTypes = nil
	file_currentStoreService_proto_depIdxs = nil
}
