// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pluginService.proto

package services

import (
	_ "github.com/geiqin/micro-kit/protobuf/common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PluginService service

func NewPluginServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PluginService service

type PluginService interface {
	//创建插件
	Create(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error)
	//修改插件
	Update(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error)
	//移除插件
	Delete(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error)
	//插件详情
	Detail(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error)
	//获取插件列表
	List(ctx context.Context, in *PluginRequest, opts ...client.CallOption) (*PluginResponse, error)
	//插件查询
	Search(ctx context.Context, in *PluginRequest, opts ...client.CallOption) (*PluginResponse, error)
}

type pluginService struct {
	c    client.Client
	name string
}

func NewPluginService(name string, c client.Client) PluginService {
	return &pluginService{
		c:    c,
		name: name,
	}
}

func (c *pluginService) Create(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error) {
	req := c.c.NewRequest(c.name, "PluginService.Create", in)
	out := new(PluginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginService) Update(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error) {
	req := c.c.NewRequest(c.name, "PluginService.Update", in)
	out := new(PluginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginService) Delete(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error) {
	req := c.c.NewRequest(c.name, "PluginService.Delete", in)
	out := new(PluginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginService) Detail(ctx context.Context, in *Plugin, opts ...client.CallOption) (*PluginResponse, error) {
	req := c.c.NewRequest(c.name, "PluginService.Detail", in)
	out := new(PluginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginService) List(ctx context.Context, in *PluginRequest, opts ...client.CallOption) (*PluginResponse, error) {
	req := c.c.NewRequest(c.name, "PluginService.List", in)
	out := new(PluginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginService) Search(ctx context.Context, in *PluginRequest, opts ...client.CallOption) (*PluginResponse, error) {
	req := c.c.NewRequest(c.name, "PluginService.Search", in)
	out := new(PluginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PluginService service

type PluginServiceHandler interface {
	//创建插件
	Create(context.Context, *Plugin, *PluginResponse) error
	//修改插件
	Update(context.Context, *Plugin, *PluginResponse) error
	//移除插件
	Delete(context.Context, *Plugin, *PluginResponse) error
	//插件详情
	Detail(context.Context, *Plugin, *PluginResponse) error
	//获取插件列表
	List(context.Context, *PluginRequest, *PluginResponse) error
	//插件查询
	Search(context.Context, *PluginRequest, *PluginResponse) error
}

func RegisterPluginServiceHandler(s server.Server, hdlr PluginServiceHandler, opts ...server.HandlerOption) error {
	type pluginService interface {
		Create(ctx context.Context, in *Plugin, out *PluginResponse) error
		Update(ctx context.Context, in *Plugin, out *PluginResponse) error
		Delete(ctx context.Context, in *Plugin, out *PluginResponse) error
		Detail(ctx context.Context, in *Plugin, out *PluginResponse) error
		List(ctx context.Context, in *PluginRequest, out *PluginResponse) error
		Search(ctx context.Context, in *PluginRequest, out *PluginResponse) error
	}
	type PluginService struct {
		pluginService
	}
	h := &pluginServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PluginService{h}, opts...))
}

type pluginServiceHandler struct {
	PluginServiceHandler
}

func (h *pluginServiceHandler) Create(ctx context.Context, in *Plugin, out *PluginResponse) error {
	return h.PluginServiceHandler.Create(ctx, in, out)
}

func (h *pluginServiceHandler) Update(ctx context.Context, in *Plugin, out *PluginResponse) error {
	return h.PluginServiceHandler.Update(ctx, in, out)
}

func (h *pluginServiceHandler) Delete(ctx context.Context, in *Plugin, out *PluginResponse) error {
	return h.PluginServiceHandler.Delete(ctx, in, out)
}

func (h *pluginServiceHandler) Detail(ctx context.Context, in *Plugin, out *PluginResponse) error {
	return h.PluginServiceHandler.Detail(ctx, in, out)
}

func (h *pluginServiceHandler) List(ctx context.Context, in *PluginRequest, out *PluginResponse) error {
	return h.PluginServiceHandler.List(ctx, in, out)
}

func (h *pluginServiceHandler) Search(ctx context.Context, in *PluginRequest, out *PluginResponse) error {
	return h.PluginServiceHandler.Search(ctx, in, out)
}
