// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: orderService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrderService service

func NewOrderServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrderService service

type OrderService interface {
	//修改价格
	ModifyPrice(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error)
	//修改地址
	ModifyAddress(ctx context.Context, in *OrderAddress, opts ...client.CallOption) (*OrderResponse, error)
	//撤销订单
	Cancel(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error)
	//删除订单
	Delete(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error)
	//订单追加备注
	AppendRemark(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//确认订单(接单/拒单操作)
	ConfirmOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//确认已收货
	ConfirmReceived(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//确认已结算操作
	//结算订单(无法通过正常流程完成订单,需要商家主动完成订单)
	//适用订单: 堂食餐后付款订单、货到付款订单、外卖餐到付款订单
	ConfirmSettled(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//扫码核销订单
	Verification(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//获取订单信息
	Get(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error)
	//显示订单信息(详细信息)
	Display(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error)
	//前端显示订单信息(详细信息)
	FrontDisplay(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error)
	//查询订单
	Search(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//按条件获取订单列表
	List(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
	//获取订单赠送\使用的优惠券列表
	GetCouponList(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) ModifyPrice(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.ModifyPrice", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) ModifyAddress(ctx context.Context, in *OrderAddress, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.ModifyAddress", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Cancel(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.Cancel", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Delete(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.Delete", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) AppendRemark(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.AppendRemark", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) ConfirmOrder(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.ConfirmOrder", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) ConfirmReceived(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.ConfirmReceived", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) ConfirmSettled(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.ConfirmSettled", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Verification(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.Verification", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Get(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.Get", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Display(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.Display", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) FrontDisplay(ctx context.Context, in *Order, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.FrontDisplay", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) Search(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.Search", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) List(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.List", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) GetCouponList(ctx context.Context, in *OrderRequest, opts ...client.CallOption) (*OrderResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.GetCouponList", in)
	out := new(OrderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	//修改价格
	ModifyPrice(context.Context, *Order, *OrderResponse) error
	//修改地址
	ModifyAddress(context.Context, *OrderAddress, *OrderResponse) error
	//撤销订单
	Cancel(context.Context, *Order, *OrderResponse) error
	//删除订单
	Delete(context.Context, *Order, *OrderResponse) error
	//订单追加备注
	AppendRemark(context.Context, *OrderRequest, *OrderResponse) error
	//确认订单(接单/拒单操作)
	ConfirmOrder(context.Context, *OrderRequest, *OrderResponse) error
	//确认已收货
	ConfirmReceived(context.Context, *OrderRequest, *OrderResponse) error
	//确认已结算操作
	//结算订单(无法通过正常流程完成订单,需要商家主动完成订单)
	//适用订单: 堂食餐后付款订单、货到付款订单、外卖餐到付款订单
	ConfirmSettled(context.Context, *OrderRequest, *OrderResponse) error
	//扫码核销订单
	Verification(context.Context, *OrderRequest, *OrderResponse) error
	//获取订单信息
	Get(context.Context, *Order, *OrderResponse) error
	//显示订单信息(详细信息)
	Display(context.Context, *Order, *OrderResponse) error
	//前端显示订单信息(详细信息)
	FrontDisplay(context.Context, *Order, *OrderResponse) error
	//查询订单
	Search(context.Context, *OrderRequest, *OrderResponse) error
	//按条件获取订单列表
	List(context.Context, *OrderRequest, *OrderResponse) error
	//获取订单赠送\使用的优惠券列表
	GetCouponList(context.Context, *OrderRequest, *OrderResponse) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) error {
	type orderService interface {
		ModifyPrice(ctx context.Context, in *Order, out *OrderResponse) error
		ModifyAddress(ctx context.Context, in *OrderAddress, out *OrderResponse) error
		Cancel(ctx context.Context, in *Order, out *OrderResponse) error
		Delete(ctx context.Context, in *Order, out *OrderResponse) error
		AppendRemark(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		ConfirmOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		ConfirmReceived(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		ConfirmSettled(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		Verification(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		Get(ctx context.Context, in *Order, out *OrderResponse) error
		Display(ctx context.Context, in *Order, out *OrderResponse) error
		FrontDisplay(ctx context.Context, in *Order, out *OrderResponse) error
		Search(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		List(ctx context.Context, in *OrderRequest, out *OrderResponse) error
		GetCouponList(ctx context.Context, in *OrderRequest, out *OrderResponse) error
	}
	type OrderService struct {
		orderService
	}
	h := &orderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderService{h}, opts...))
}

type orderServiceHandler struct {
	OrderServiceHandler
}

func (h *orderServiceHandler) ModifyPrice(ctx context.Context, in *Order, out *OrderResponse) error {
	return h.OrderServiceHandler.ModifyPrice(ctx, in, out)
}

func (h *orderServiceHandler) ModifyAddress(ctx context.Context, in *OrderAddress, out *OrderResponse) error {
	return h.OrderServiceHandler.ModifyAddress(ctx, in, out)
}

func (h *orderServiceHandler) Cancel(ctx context.Context, in *Order, out *OrderResponse) error {
	return h.OrderServiceHandler.Cancel(ctx, in, out)
}

func (h *orderServiceHandler) Delete(ctx context.Context, in *Order, out *OrderResponse) error {
	return h.OrderServiceHandler.Delete(ctx, in, out)
}

func (h *orderServiceHandler) AppendRemark(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.AppendRemark(ctx, in, out)
}

func (h *orderServiceHandler) ConfirmOrder(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.ConfirmOrder(ctx, in, out)
}

func (h *orderServiceHandler) ConfirmReceived(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.ConfirmReceived(ctx, in, out)
}

func (h *orderServiceHandler) ConfirmSettled(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.ConfirmSettled(ctx, in, out)
}

func (h *orderServiceHandler) Verification(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.Verification(ctx, in, out)
}

func (h *orderServiceHandler) Get(ctx context.Context, in *Order, out *OrderResponse) error {
	return h.OrderServiceHandler.Get(ctx, in, out)
}

func (h *orderServiceHandler) Display(ctx context.Context, in *Order, out *OrderResponse) error {
	return h.OrderServiceHandler.Display(ctx, in, out)
}

func (h *orderServiceHandler) FrontDisplay(ctx context.Context, in *Order, out *OrderResponse) error {
	return h.OrderServiceHandler.FrontDisplay(ctx, in, out)
}

func (h *orderServiceHandler) Search(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.Search(ctx, in, out)
}

func (h *orderServiceHandler) List(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.List(ctx, in, out)
}

func (h *orderServiceHandler) GetCouponList(ctx context.Context, in *OrderRequest, out *OrderResponse) error {
	return h.OrderServiceHandler.GetCouponList(ctx, in, out)
}
