// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: orderPaidLogService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrderPaidLogService service

func NewOrderPaidLogServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrderPaidLogService service

type OrderPaidLogService interface {
	Get(ctx context.Context, in *OrderPaidLog, opts ...client.CallOption) (*OrderPaidLogResponse, error)
	Search(ctx context.Context, in *OrderPaidLogRequest, opts ...client.CallOption) (*OrderPaidLogResponse, error)
}

type orderPaidLogService struct {
	c    client.Client
	name string
}

func NewOrderPaidLogService(name string, c client.Client) OrderPaidLogService {
	return &orderPaidLogService{
		c:    c,
		name: name,
	}
}

func (c *orderPaidLogService) Get(ctx context.Context, in *OrderPaidLog, opts ...client.CallOption) (*OrderPaidLogResponse, error) {
	req := c.c.NewRequest(c.name, "OrderPaidLogService.Get", in)
	out := new(OrderPaidLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderPaidLogService) Search(ctx context.Context, in *OrderPaidLogRequest, opts ...client.CallOption) (*OrderPaidLogResponse, error) {
	req := c.c.NewRequest(c.name, "OrderPaidLogService.Search", in)
	out := new(OrderPaidLogResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderPaidLogService service

type OrderPaidLogServiceHandler interface {
	Get(context.Context, *OrderPaidLog, *OrderPaidLogResponse) error
	Search(context.Context, *OrderPaidLogRequest, *OrderPaidLogResponse) error
}

func RegisterOrderPaidLogServiceHandler(s server.Server, hdlr OrderPaidLogServiceHandler, opts ...server.HandlerOption) error {
	type orderPaidLogService interface {
		Get(ctx context.Context, in *OrderPaidLog, out *OrderPaidLogResponse) error
		Search(ctx context.Context, in *OrderPaidLogRequest, out *OrderPaidLogResponse) error
	}
	type OrderPaidLogService struct {
		orderPaidLogService
	}
	h := &orderPaidLogServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderPaidLogService{h}, opts...))
}

type orderPaidLogServiceHandler struct {
	OrderPaidLogServiceHandler
}

func (h *orderPaidLogServiceHandler) Get(ctx context.Context, in *OrderPaidLog, out *OrderPaidLogResponse) error {
	return h.OrderPaidLogServiceHandler.Get(ctx, in, out)
}

func (h *orderPaidLogServiceHandler) Search(ctx context.Context, in *OrderPaidLogRequest, out *OrderPaidLogResponse) error {
	return h.OrderPaidLogServiceHandler.Search(ctx, in, out)
}
