// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: orderPacketService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OrderPacketService service

func NewOrderPacketServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for OrderPacketService service

type OrderPacketService interface {
	Detail(ctx context.Context, in *OrderPacket, opts ...client.CallOption) (*OrderPacketResponse, error)
	Search(ctx context.Context, in *OrderPacketRequest, opts ...client.CallOption) (*OrderPacketResponse, error)
}

type orderPacketService struct {
	c    client.Client
	name string
}

func NewOrderPacketService(name string, c client.Client) OrderPacketService {
	return &orderPacketService{
		c:    c,
		name: name,
	}
}

func (c *orderPacketService) Detail(ctx context.Context, in *OrderPacket, opts ...client.CallOption) (*OrderPacketResponse, error) {
	req := c.c.NewRequest(c.name, "OrderPacketService.Detail", in)
	out := new(OrderPacketResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderPacketService) Search(ctx context.Context, in *OrderPacketRequest, opts ...client.CallOption) (*OrderPacketResponse, error) {
	req := c.c.NewRequest(c.name, "OrderPacketService.Search", in)
	out := new(OrderPacketResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderPacketService service

type OrderPacketServiceHandler interface {
	Detail(context.Context, *OrderPacket, *OrderPacketResponse) error
	Search(context.Context, *OrderPacketRequest, *OrderPacketResponse) error
}

func RegisterOrderPacketServiceHandler(s server.Server, hdlr OrderPacketServiceHandler, opts ...server.HandlerOption) error {
	type orderPacketService interface {
		Detail(ctx context.Context, in *OrderPacket, out *OrderPacketResponse) error
		Search(ctx context.Context, in *OrderPacketRequest, out *OrderPacketResponse) error
	}
	type OrderPacketService struct {
		orderPacketService
	}
	h := &orderPacketServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderPacketService{h}, opts...))
}

type orderPacketServiceHandler struct {
	OrderPacketServiceHandler
}

func (h *orderPacketServiceHandler) Detail(ctx context.Context, in *OrderPacket, out *OrderPacketResponse) error {
	return h.OrderPacketServiceHandler.Detail(ctx, in, out)
}

func (h *orderPacketServiceHandler) Search(ctx context.Context, in *OrderPacketRequest, out *OrderPacketResponse) error {
	return h.OrderPacketServiceHandler.Search(ctx, in, out)
}
