// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: agreementConfigService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AgreementConfigService service

func NewAgreementConfigServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AgreementConfigService service

type AgreementConfigService interface {
	Set(ctx context.Context, in *AgreementConfig, opts ...client.CallOption) (*AgreementConfigResponse, error)
	Get(ctx context.Context, in *AgreementConfig, opts ...client.CallOption) (*AgreementConfigResponse, error)
}

type agreementConfigService struct {
	c    client.Client
	name string
}

func NewAgreementConfigService(name string, c client.Client) AgreementConfigService {
	return &agreementConfigService{
		c:    c,
		name: name,
	}
}

func (c *agreementConfigService) Set(ctx context.Context, in *AgreementConfig, opts ...client.CallOption) (*AgreementConfigResponse, error) {
	req := c.c.NewRequest(c.name, "AgreementConfigService.Set", in)
	out := new(AgreementConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agreementConfigService) Get(ctx context.Context, in *AgreementConfig, opts ...client.CallOption) (*AgreementConfigResponse, error) {
	req := c.c.NewRequest(c.name, "AgreementConfigService.Get", in)
	out := new(AgreementConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgreementConfigService service

type AgreementConfigServiceHandler interface {
	Set(context.Context, *AgreementConfig, *AgreementConfigResponse) error
	Get(context.Context, *AgreementConfig, *AgreementConfigResponse) error
}

func RegisterAgreementConfigServiceHandler(s server.Server, hdlr AgreementConfigServiceHandler, opts ...server.HandlerOption) error {
	type agreementConfigService interface {
		Set(ctx context.Context, in *AgreementConfig, out *AgreementConfigResponse) error
		Get(ctx context.Context, in *AgreementConfig, out *AgreementConfigResponse) error
	}
	type AgreementConfigService struct {
		agreementConfigService
	}
	h := &agreementConfigServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AgreementConfigService{h}, opts...))
}

type agreementConfigServiceHandler struct {
	AgreementConfigServiceHandler
}

func (h *agreementConfigServiceHandler) Set(ctx context.Context, in *AgreementConfig, out *AgreementConfigResponse) error {
	return h.AgreementConfigServiceHandler.Set(ctx, in, out)
}

func (h *agreementConfigServiceHandler) Get(ctx context.Context, in *AgreementConfig, out *AgreementConfigResponse) error {
	return h.AgreementConfigServiceHandler.Get(ctx, in, out)
}
