// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: emailConfigService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for EmailConfigService service

func NewEmailConfigServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for EmailConfigService service

type EmailConfigService interface {
	Set(ctx context.Context, in *EmailConfig, opts ...client.CallOption) (*EmailConfigResponse, error)
	Get(ctx context.Context, in *EmailConfig, opts ...client.CallOption) (*EmailConfigResponse, error)
}

type emailConfigService struct {
	c    client.Client
	name string
}

func NewEmailConfigService(name string, c client.Client) EmailConfigService {
	return &emailConfigService{
		c:    c,
		name: name,
	}
}

func (c *emailConfigService) Set(ctx context.Context, in *EmailConfig, opts ...client.CallOption) (*EmailConfigResponse, error) {
	req := c.c.NewRequest(c.name, "EmailConfigService.Set", in)
	out := new(EmailConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailConfigService) Get(ctx context.Context, in *EmailConfig, opts ...client.CallOption) (*EmailConfigResponse, error) {
	req := c.c.NewRequest(c.name, "EmailConfigService.Get", in)
	out := new(EmailConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailConfigService service

type EmailConfigServiceHandler interface {
	Set(context.Context, *EmailConfig, *EmailConfigResponse) error
	Get(context.Context, *EmailConfig, *EmailConfigResponse) error
}

func RegisterEmailConfigServiceHandler(s server.Server, hdlr EmailConfigServiceHandler, opts ...server.HandlerOption) error {
	type emailConfigService interface {
		Set(ctx context.Context, in *EmailConfig, out *EmailConfigResponse) error
		Get(ctx context.Context, in *EmailConfig, out *EmailConfigResponse) error
	}
	type EmailConfigService struct {
		emailConfigService
	}
	h := &emailConfigServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&EmailConfigService{h}, opts...))
}

type emailConfigServiceHandler struct {
	EmailConfigServiceHandler
}

func (h *emailConfigServiceHandler) Set(ctx context.Context, in *EmailConfig, out *EmailConfigResponse) error {
	return h.EmailConfigServiceHandler.Set(ctx, in, out)
}

func (h *emailConfigServiceHandler) Get(ctx context.Context, in *EmailConfig, out *EmailConfigResponse) error {
	return h.EmailConfigServiceHandler.Get(ctx, in, out)
}
