// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pcConfigService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PcConfigService service

func NewPcConfigServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for PcConfigService service

type PcConfigService interface {
	//获取
	Get(ctx context.Context, in *PcConfig, opts ...client.CallOption) (*PcConfigResponse, error)
	//保存
	Save(ctx context.Context, in *PcConfig, opts ...client.CallOption) (*PcConfigResponse, error)
}

type pcConfigService struct {
	c    client.Client
	name string
}

func NewPcConfigService(name string, c client.Client) PcConfigService {
	return &pcConfigService{
		c:    c,
		name: name,
	}
}

func (c *pcConfigService) Get(ctx context.Context, in *PcConfig, opts ...client.CallOption) (*PcConfigResponse, error) {
	req := c.c.NewRequest(c.name, "PcConfigService.Get", in)
	out := new(PcConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pcConfigService) Save(ctx context.Context, in *PcConfig, opts ...client.CallOption) (*PcConfigResponse, error) {
	req := c.c.NewRequest(c.name, "PcConfigService.Save", in)
	out := new(PcConfigResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PcConfigService service

type PcConfigServiceHandler interface {
	//获取
	Get(context.Context, *PcConfig, *PcConfigResponse) error
	//保存
	Save(context.Context, *PcConfig, *PcConfigResponse) error
}

func RegisterPcConfigServiceHandler(s server.Server, hdlr PcConfigServiceHandler, opts ...server.HandlerOption) error {
	type pcConfigService interface {
		Get(ctx context.Context, in *PcConfig, out *PcConfigResponse) error
		Save(ctx context.Context, in *PcConfig, out *PcConfigResponse) error
	}
	type PcConfigService struct {
		pcConfigService
	}
	h := &pcConfigServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PcConfigService{h}, opts...))
}

type pcConfigServiceHandler struct {
	PcConfigServiceHandler
}

func (h *pcConfigServiceHandler) Get(ctx context.Context, in *PcConfig, out *PcConfigResponse) error {
	return h.PcConfigServiceHandler.Get(ctx, in, out)
}

func (h *pcConfigServiceHandler) Save(ctx context.Context, in *PcConfig, out *PcConfigResponse) error {
	return h.PcConfigServiceHandler.Save(ctx, in, out)
}
