// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: teamService.proto

package services

import (
	_ "../common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for TeamService service

func NewTeamServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for TeamService service

type TeamService interface {
	//查询团队列表
	Search(ctx context.Context, in *TeamRequest, opts ...client.CallOption) (*TeamResponse, error)
}

type teamService struct {
	c    client.Client
	name string
}

func NewTeamService(name string, c client.Client) TeamService {
	return &teamService{
		c:    c,
		name: name,
	}
}

func (c *teamService) Search(ctx context.Context, in *TeamRequest, opts ...client.CallOption) (*TeamResponse, error) {
	req := c.c.NewRequest(c.name, "TeamService.Search", in)
	out := new(TeamResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TeamService service

type TeamServiceHandler interface {
	//查询团队列表
	Search(context.Context, *TeamRequest, *TeamResponse) error
}

func RegisterTeamServiceHandler(s server.Server, hdlr TeamServiceHandler, opts ...server.HandlerOption) error {
	type teamService interface {
		Search(ctx context.Context, in *TeamRequest, out *TeamResponse) error
	}
	type TeamService struct {
		teamService
	}
	h := &teamServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&TeamService{h}, opts...))
}

type teamServiceHandler struct {
	TeamServiceHandler
}

func (h *teamServiceHandler) Search(ctx context.Context, in *TeamRequest, out *TeamResponse) error {
	return h.TeamServiceHandler.Search(ctx, in, out)
}
