// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userSelfExtractionService.proto

package services

import (
	_ "../common"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserSelfExtractionService service

func NewUserSelfExtractionServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserSelfExtractionService service

type UserSelfExtractionService interface {
	Create(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error)
	Update(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error)
	Delete(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error)
	Get(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error)
	List(ctx context.Context, in *UserSelfExtractionRequest, opts ...client.CallOption) (*UserSelfExtractionResponse, error)
	Search(ctx context.Context, in *UserSelfExtractionRequest, opts ...client.CallOption) (*UserSelfExtractionResponse, error)
}

type userSelfExtractionService struct {
	c    client.Client
	name string
}

func NewUserSelfExtractionService(name string, c client.Client) UserSelfExtractionService {
	return &userSelfExtractionService{
		c:    c,
		name: name,
	}
}

func (c *userSelfExtractionService) Create(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "UserSelfExtractionService.Create", in)
	out := new(UserSelfExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSelfExtractionService) Update(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "UserSelfExtractionService.Update", in)
	out := new(UserSelfExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSelfExtractionService) Delete(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "UserSelfExtractionService.Delete", in)
	out := new(UserSelfExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSelfExtractionService) Get(ctx context.Context, in *UserSelfExtraction, opts ...client.CallOption) (*UserSelfExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "UserSelfExtractionService.Get", in)
	out := new(UserSelfExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSelfExtractionService) List(ctx context.Context, in *UserSelfExtractionRequest, opts ...client.CallOption) (*UserSelfExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "UserSelfExtractionService.List", in)
	out := new(UserSelfExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSelfExtractionService) Search(ctx context.Context, in *UserSelfExtractionRequest, opts ...client.CallOption) (*UserSelfExtractionResponse, error) {
	req := c.c.NewRequest(c.name, "UserSelfExtractionService.Search", in)
	out := new(UserSelfExtractionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserSelfExtractionService service

type UserSelfExtractionServiceHandler interface {
	Create(context.Context, *UserSelfExtraction, *UserSelfExtractionResponse) error
	Update(context.Context, *UserSelfExtraction, *UserSelfExtractionResponse) error
	Delete(context.Context, *UserSelfExtraction, *UserSelfExtractionResponse) error
	Get(context.Context, *UserSelfExtraction, *UserSelfExtractionResponse) error
	List(context.Context, *UserSelfExtractionRequest, *UserSelfExtractionResponse) error
	Search(context.Context, *UserSelfExtractionRequest, *UserSelfExtractionResponse) error
}

func RegisterUserSelfExtractionServiceHandler(s server.Server, hdlr UserSelfExtractionServiceHandler, opts ...server.HandlerOption) error {
	type userSelfExtractionService interface {
		Create(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error
		Update(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error
		Delete(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error
		Get(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error
		List(ctx context.Context, in *UserSelfExtractionRequest, out *UserSelfExtractionResponse) error
		Search(ctx context.Context, in *UserSelfExtractionRequest, out *UserSelfExtractionResponse) error
	}
	type UserSelfExtractionService struct {
		userSelfExtractionService
	}
	h := &userSelfExtractionServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserSelfExtractionService{h}, opts...))
}

type userSelfExtractionServiceHandler struct {
	UserSelfExtractionServiceHandler
}

func (h *userSelfExtractionServiceHandler) Create(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error {
	return h.UserSelfExtractionServiceHandler.Create(ctx, in, out)
}

func (h *userSelfExtractionServiceHandler) Update(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error {
	return h.UserSelfExtractionServiceHandler.Update(ctx, in, out)
}

func (h *userSelfExtractionServiceHandler) Delete(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error {
	return h.UserSelfExtractionServiceHandler.Delete(ctx, in, out)
}

func (h *userSelfExtractionServiceHandler) Get(ctx context.Context, in *UserSelfExtraction, out *UserSelfExtractionResponse) error {
	return h.UserSelfExtractionServiceHandler.Get(ctx, in, out)
}

func (h *userSelfExtractionServiceHandler) List(ctx context.Context, in *UserSelfExtractionRequest, out *UserSelfExtractionResponse) error {
	return h.UserSelfExtractionServiceHandler.List(ctx, in, out)
}

func (h *userSelfExtractionServiceHandler) Search(ctx context.Context, in *UserSelfExtractionRequest, out *UserSelfExtractionResponse) error {
	return h.UserSelfExtractionServiceHandler.Search(ctx, in, out)
}
