// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: uploadService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UploadService service

func NewUploadServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UploadService service

type UploadService interface {
	// 获取上传凭证【服务专用】
	GetToken(ctx context.Context, in *UploadTokenRequest, opts ...client.CallOption) (*UploadResponse, error)
	// 删除文件【服务专用】
	RemoveKey(ctx context.Context, in *RemoveKeyRequest, opts ...client.CallOption) (*UploadResponse, error)
	// 抓取第三方资源【服务专用】
	Fetch(ctx context.Context, in *FetchRequest, opts ...client.CallOption) (*UploadResponse, error)
}

type uploadService struct {
	c    client.Client
	name string
}

func NewUploadService(name string, c client.Client) UploadService {
	return &uploadService{
		c:    c,
		name: name,
	}
}

func (c *uploadService) GetToken(ctx context.Context, in *UploadTokenRequest, opts ...client.CallOption) (*UploadResponse, error) {
	req := c.c.NewRequest(c.name, "UploadService.GetToken", in)
	out := new(UploadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadService) RemoveKey(ctx context.Context, in *RemoveKeyRequest, opts ...client.CallOption) (*UploadResponse, error) {
	req := c.c.NewRequest(c.name, "UploadService.RemoveKey", in)
	out := new(UploadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadService) Fetch(ctx context.Context, in *FetchRequest, opts ...client.CallOption) (*UploadResponse, error) {
	req := c.c.NewRequest(c.name, "UploadService.Fetch", in)
	out := new(UploadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UploadService service

type UploadServiceHandler interface {
	// 获取上传凭证【服务专用】
	GetToken(context.Context, *UploadTokenRequest, *UploadResponse) error
	// 删除文件【服务专用】
	RemoveKey(context.Context, *RemoveKeyRequest, *UploadResponse) error
	// 抓取第三方资源【服务专用】
	Fetch(context.Context, *FetchRequest, *UploadResponse) error
}

func RegisterUploadServiceHandler(s server.Server, hdlr UploadServiceHandler, opts ...server.HandlerOption) error {
	type uploadService interface {
		GetToken(ctx context.Context, in *UploadTokenRequest, out *UploadResponse) error
		RemoveKey(ctx context.Context, in *RemoveKeyRequest, out *UploadResponse) error
		Fetch(ctx context.Context, in *FetchRequest, out *UploadResponse) error
	}
	type UploadService struct {
		uploadService
	}
	h := &uploadServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UploadService{h}, opts...))
}

type uploadServiceHandler struct {
	UploadServiceHandler
}

func (h *uploadServiceHandler) GetToken(ctx context.Context, in *UploadTokenRequest, out *UploadResponse) error {
	return h.UploadServiceHandler.GetToken(ctx, in, out)
}

func (h *uploadServiceHandler) RemoveKey(ctx context.Context, in *RemoveKeyRequest, out *UploadResponse) error {
	return h.UploadServiceHandler.RemoveKey(ctx, in, out)
}

func (h *uploadServiceHandler) Fetch(ctx context.Context, in *FetchRequest, out *UploadResponse) error {
	return h.UploadServiceHandler.Fetch(ctx, in, out)
}
