// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: vipBenefitService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for VipBenefitService service

func NewVipBenefitServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for VipBenefitService service

type VipBenefitService interface {
	// VIP权益新增
	Create(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error)
	// VIP权益修改
	Update(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error)
	// VIP权益删除
	Delete(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error)
	// VIP权益获取
	Get(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error)
	// VIP权益查询
	Search(ctx context.Context, in *VipBenefitRequest, opts ...client.CallOption) (*VipBenefitResponse, error)
	// VIP权益列表
	List(ctx context.Context, in *VipBenefitRequest, opts ...client.CallOption) (*VipBenefitResponse, error)
}

type vipBenefitService struct {
	c    client.Client
	name string
}

func NewVipBenefitService(name string, c client.Client) VipBenefitService {
	return &vipBenefitService{
		c:    c,
		name: name,
	}
}

func (c *vipBenefitService) Create(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error) {
	req := c.c.NewRequest(c.name, "VipBenefitService.Create", in)
	out := new(VipBenefitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipBenefitService) Update(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error) {
	req := c.c.NewRequest(c.name, "VipBenefitService.Update", in)
	out := new(VipBenefitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipBenefitService) Delete(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error) {
	req := c.c.NewRequest(c.name, "VipBenefitService.Delete", in)
	out := new(VipBenefitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipBenefitService) Get(ctx context.Context, in *VipBenefit, opts ...client.CallOption) (*VipBenefitResponse, error) {
	req := c.c.NewRequest(c.name, "VipBenefitService.Get", in)
	out := new(VipBenefitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipBenefitService) Search(ctx context.Context, in *VipBenefitRequest, opts ...client.CallOption) (*VipBenefitResponse, error) {
	req := c.c.NewRequest(c.name, "VipBenefitService.Search", in)
	out := new(VipBenefitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vipBenefitService) List(ctx context.Context, in *VipBenefitRequest, opts ...client.CallOption) (*VipBenefitResponse, error) {
	req := c.c.NewRequest(c.name, "VipBenefitService.List", in)
	out := new(VipBenefitResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VipBenefitService service

type VipBenefitServiceHandler interface {
	// VIP权益新增
	Create(context.Context, *VipBenefit, *VipBenefitResponse) error
	// VIP权益修改
	Update(context.Context, *VipBenefit, *VipBenefitResponse) error
	// VIP权益删除
	Delete(context.Context, *VipBenefit, *VipBenefitResponse) error
	// VIP权益获取
	Get(context.Context, *VipBenefit, *VipBenefitResponse) error
	// VIP权益查询
	Search(context.Context, *VipBenefitRequest, *VipBenefitResponse) error
	// VIP权益列表
	List(context.Context, *VipBenefitRequest, *VipBenefitResponse) error
}

func RegisterVipBenefitServiceHandler(s server.Server, hdlr VipBenefitServiceHandler, opts ...server.HandlerOption) error {
	type vipBenefitService interface {
		Create(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error
		Update(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error
		Delete(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error
		Get(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error
		Search(ctx context.Context, in *VipBenefitRequest, out *VipBenefitResponse) error
		List(ctx context.Context, in *VipBenefitRequest, out *VipBenefitResponse) error
	}
	type VipBenefitService struct {
		vipBenefitService
	}
	h := &vipBenefitServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&VipBenefitService{h}, opts...))
}

type vipBenefitServiceHandler struct {
	VipBenefitServiceHandler
}

func (h *vipBenefitServiceHandler) Create(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error {
	return h.VipBenefitServiceHandler.Create(ctx, in, out)
}

func (h *vipBenefitServiceHandler) Update(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error {
	return h.VipBenefitServiceHandler.Update(ctx, in, out)
}

func (h *vipBenefitServiceHandler) Delete(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error {
	return h.VipBenefitServiceHandler.Delete(ctx, in, out)
}

func (h *vipBenefitServiceHandler) Get(ctx context.Context, in *VipBenefit, out *VipBenefitResponse) error {
	return h.VipBenefitServiceHandler.Get(ctx, in, out)
}

func (h *vipBenefitServiceHandler) Search(ctx context.Context, in *VipBenefitRequest, out *VipBenefitResponse) error {
	return h.VipBenefitServiceHandler.Search(ctx, in, out)
}

func (h *vipBenefitServiceHandler) List(ctx context.Context, in *VipBenefitRequest, out *VipBenefitResponse) error {
	return h.VipBenefitServiceHandler.List(ctx, in, out)
}
