// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: spuService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SpuService service

func NewSpuServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SpuService service

type SpuService interface {
	Create(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error)
	Update(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error)
	Delete(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error)
	Get(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error)
	Search(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error)
	//商品上下架
	Sale(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error)
	//显示商品详情
	Display(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error)
	//商品排序
	Sort(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error)
}

type spuService struct {
	c    client.Client
	name string
}

func NewSpuService(name string, c client.Client) SpuService {
	return &spuService{
		c:    c,
		name: name,
	}
}

func (c *spuService) Create(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Create", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Update(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Update", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Delete(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Delete", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Get(ctx context.Context, in *Spu, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Get", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Search(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Search", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Sale(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Sale", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Display(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Display", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spuService) Sort(ctx context.Context, in *SpuRequest, opts ...client.CallOption) (*SpuResponse, error) {
	req := c.c.NewRequest(c.name, "SpuService.Sort", in)
	out := new(SpuResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SpuService service

type SpuServiceHandler interface {
	Create(context.Context, *Spu, *SpuResponse) error
	Update(context.Context, *Spu, *SpuResponse) error
	Delete(context.Context, *Spu, *SpuResponse) error
	Get(context.Context, *Spu, *SpuResponse) error
	Search(context.Context, *SpuRequest, *SpuResponse) error
	//商品上下架
	Sale(context.Context, *SpuRequest, *SpuResponse) error
	//显示商品详情
	Display(context.Context, *SpuRequest, *SpuResponse) error
	//商品排序
	Sort(context.Context, *SpuRequest, *SpuResponse) error
}

func RegisterSpuServiceHandler(s server.Server, hdlr SpuServiceHandler, opts ...server.HandlerOption) error {
	type spuService interface {
		Create(ctx context.Context, in *Spu, out *SpuResponse) error
		Update(ctx context.Context, in *Spu, out *SpuResponse) error
		Delete(ctx context.Context, in *Spu, out *SpuResponse) error
		Get(ctx context.Context, in *Spu, out *SpuResponse) error
		Search(ctx context.Context, in *SpuRequest, out *SpuResponse) error
		Sale(ctx context.Context, in *SpuRequest, out *SpuResponse) error
		Display(ctx context.Context, in *SpuRequest, out *SpuResponse) error
		Sort(ctx context.Context, in *SpuRequest, out *SpuResponse) error
	}
	type SpuService struct {
		spuService
	}
	h := &spuServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SpuService{h}, opts...))
}

type spuServiceHandler struct {
	SpuServiceHandler
}

func (h *spuServiceHandler) Create(ctx context.Context, in *Spu, out *SpuResponse) error {
	return h.SpuServiceHandler.Create(ctx, in, out)
}

func (h *spuServiceHandler) Update(ctx context.Context, in *Spu, out *SpuResponse) error {
	return h.SpuServiceHandler.Update(ctx, in, out)
}

func (h *spuServiceHandler) Delete(ctx context.Context, in *Spu, out *SpuResponse) error {
	return h.SpuServiceHandler.Delete(ctx, in, out)
}

func (h *spuServiceHandler) Get(ctx context.Context, in *Spu, out *SpuResponse) error {
	return h.SpuServiceHandler.Get(ctx, in, out)
}

func (h *spuServiceHandler) Search(ctx context.Context, in *SpuRequest, out *SpuResponse) error {
	return h.SpuServiceHandler.Search(ctx, in, out)
}

func (h *spuServiceHandler) Sale(ctx context.Context, in *SpuRequest, out *SpuResponse) error {
	return h.SpuServiceHandler.Sale(ctx, in, out)
}

func (h *spuServiceHandler) Display(ctx context.Context, in *SpuRequest, out *SpuResponse) error {
	return h.SpuServiceHandler.Display(ctx, in, out)
}

func (h *spuServiceHandler) Sort(ctx context.Context, in *SpuRequest, out *SpuResponse) error {
	return h.SpuServiceHandler.Sort(ctx, in, out)
}
