// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: warehouseGoodsService.proto

package services

import (
	common "github.com/geiqin/micro-kit/protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarehouseGoods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`                                      //ID
	WarehouseId   int64                  `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id"` //仓库id
	SpuId         int64                  `protobuf:"varint,3,opt,name=spu_id,json=spuId,proto3" json:"spu_id"`                   //商品id
	Inventory     int64                  `protobuf:"varint,4,opt,name=inventory,proto3" json:"inventory"`                        //总库存
	IsEnable      string                 `protobuf:"bytes,5,opt,name=is_enable,json=isEnable,proto3" json:"is_enable"`           //是否启用（0否，1是）
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Warehouse     *Warehouse             `protobuf:"bytes,9,opt,name=warehouse,proto3" json:"warehouse"`
	Spu           *Spu                   `protobuf:"bytes,10,opt,name=spu,proto3" json:"spu"`
	SpecList      []*WarehouseGoodsSpec  `protobuf:"bytes,11,rep,name=spec_list,json=specList,proto3" json:"spec_list"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseGoods) Reset() {
	*x = WarehouseGoods{}
	mi := &file_warehouseGoodsService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseGoods) ProtoMessage() {}

func (x *WarehouseGoods) ProtoReflect() protoreflect.Message {
	mi := &file_warehouseGoodsService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseGoods.ProtoReflect.Descriptor instead.
func (*WarehouseGoods) Descriptor() ([]byte, []int) {
	return file_warehouseGoodsService_proto_rawDescGZIP(), []int{0}
}

func (x *WarehouseGoods) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WarehouseGoods) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *WarehouseGoods) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *WarehouseGoods) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *WarehouseGoods) GetIsEnable() string {
	if x != nil {
		return x.IsEnable
	}
	return ""
}

func (x *WarehouseGoods) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WarehouseGoods) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *WarehouseGoods) GetWarehouse() *Warehouse {
	if x != nil {
		return x.Warehouse
	}
	return nil
}

func (x *WarehouseGoods) GetSpu() *Spu {
	if x != nil {
		return x.Spu
	}
	return nil
}

func (x *WarehouseGoods) GetSpecList() []*WarehouseGoodsSpec {
	if x != nil {
		return x.SpecList
	}
	return nil
}

type WarehouseGoodsSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`                                                       //ID
	WarehouseGoodsId int64                  `protobuf:"varint,2,opt,name=warehouse_goods_id,json=warehouseGoodsId,proto3" json:"warehouse_goods_id"` //仓库商品id
	WarehouseId      int64                  `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id"`                  //仓库id
	SpuId            int64                  `protobuf:"varint,4,opt,name=spu_id,json=spuId,proto3" json:"spu_id"`                                    //商品id
	Unique           string                 `protobuf:"bytes,5,opt,name=unique,proto3" json:"unique"`                                                //SKUKey
	Inventory        int64                  `protobuf:"varint,6,opt,name=inventory,proto3" json:"inventory"`                                         //库存
	Spec             []*SkuSpecInfo         `protobuf:"bytes,7,rep,name=spec,proto3" json:"spec"`                                                    //规格值
	SpecDesc         string                 `protobuf:"bytes,8,opt,name=spec_desc,json=specDesc,proto3" json:"spec_desc"`
	CreatedAt        int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt        int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	Sku              *Sku                   `protobuf:"bytes,12,opt,name=sku,proto3" json:"sku"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WarehouseGoodsSpec) Reset() {
	*x = WarehouseGoodsSpec{}
	mi := &file_warehouseGoodsService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseGoodsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseGoodsSpec) ProtoMessage() {}

func (x *WarehouseGoodsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_warehouseGoodsService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseGoodsSpec.ProtoReflect.Descriptor instead.
func (*WarehouseGoodsSpec) Descriptor() ([]byte, []int) {
	return file_warehouseGoodsService_proto_rawDescGZIP(), []int{1}
}

func (x *WarehouseGoodsSpec) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetWarehouseGoodsId() int64 {
	if x != nil {
		return x.WarehouseGoodsId
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetUnique() string {
	if x != nil {
		return x.Unique
	}
	return ""
}

func (x *WarehouseGoodsSpec) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetSpec() []*SkuSpecInfo {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *WarehouseGoodsSpec) GetSpecDesc() string {
	if x != nil {
		return x.SpecDesc
	}
	return ""
}

func (x *WarehouseGoodsSpec) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *WarehouseGoodsSpec) GetSku() *Sku {
	if x != nil {
		return x.Sku
	}
	return nil
}

type WarehouseGoodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paged         int64                  `protobuf:"varint,1,opt,name=paged,proto3" json:"paged"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	Sorting       string                 `protobuf:"bytes,3,opt,name=sorting,proto3" json:"sorting"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id"`
	WarehouseId   int64                  `protobuf:"varint,5,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id"` //仓库id
	SpuId         int64                  `protobuf:"varint,6,opt,name=spu_id,json=spuId,proto3" json:"spu_id"`                   //商品id
	Inventory     int64                  `protobuf:"varint,7,opt,name=inventory,proto3" json:"inventory"`                        //总库存
	IsEnable      string                 `protobuf:"bytes,8,opt,name=is_enable,json=isEnable,proto3" json:"is_enable"`           //是否启用（0否，1是）
	CategoryId    int64                  `protobuf:"varint,9,opt,name=category_id,json=categoryId,proto3" json:"category_id"`    //商品分类ID
	BrandId       int32                  `protobuf:"varint,10,opt,name=brand_id,json=brandId,proto3" json:"brand_id"`            //品牌ID
	ShopId        int64                  `protobuf:"varint,11,opt,name=shop_id,json=shopId,proto3" json:"shop_id"`               //分店ID
	GroupId       int64                  `protobuf:"varint,12,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Name          string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name"`         //商品名称
	Keywords      string                 `protobuf:"bytes,14,opt,name=keywords,proto3" json:"keywords"` //商品标题
	Ids           []int64                `protobuf:"varint,15,rep,packed,name=ids,proto3" json:"ids"`
	SpuIds        []int64                `protobuf:"varint,16,rep,packed,name=spu_ids,json=spuIds,proto3" json:"spu_ids"`
	GroupIds      []int64                `protobuf:"varint,17,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseGoodsRequest) Reset() {
	*x = WarehouseGoodsRequest{}
	mi := &file_warehouseGoodsService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseGoodsRequest) ProtoMessage() {}

func (x *WarehouseGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warehouseGoodsService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseGoodsRequest.ProtoReflect.Descriptor instead.
func (*WarehouseGoodsRequest) Descriptor() ([]byte, []int) {
	return file_warehouseGoodsService_proto_rawDescGZIP(), []int{2}
}

func (x *WarehouseGoodsRequest) GetPaged() int64 {
	if x != nil {
		return x.Paged
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetSorting() string {
	if x != nil {
		return x.Sorting
	}
	return ""
}

func (x *WarehouseGoodsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetSpuId() int64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetIsEnable() string {
	if x != nil {
		return x.IsEnable
	}
	return ""
}

func (x *WarehouseGoodsRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetShopId() int64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *WarehouseGoodsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WarehouseGoodsRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *WarehouseGoodsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *WarehouseGoodsRequest) GetSpuIds() []int64 {
	if x != nil {
		return x.SpuIds
	}
	return nil
}

func (x *WarehouseGoodsRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type WarehouseGoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *WarehouseGoods        `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity"`
	Pager         *common.Pager          `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager"`
	Items         []*WarehouseGoods      `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseGoodsResponse) Reset() {
	*x = WarehouseGoodsResponse{}
	mi := &file_warehouseGoodsService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseGoodsResponse) ProtoMessage() {}

func (x *WarehouseGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouseGoodsService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseGoodsResponse.ProtoReflect.Descriptor instead.
func (*WarehouseGoodsResponse) Descriptor() ([]byte, []int) {
	return file_warehouseGoodsService_proto_rawDescGZIP(), []int{3}
}

func (x *WarehouseGoodsResponse) GetEntity() *WarehouseGoods {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *WarehouseGoodsResponse) GetPager() *common.Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

func (x *WarehouseGoodsResponse) GetItems() []*WarehouseGoods {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *WarehouseGoodsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type WarehouseGoodsSelectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pager         *common.Pager          `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager"`
	Items         []*Spu                 `protobuf:"bytes,3,rep,name=items,proto3" json:"items"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseGoodsSelectorResponse) Reset() {
	*x = WarehouseGoodsSelectorResponse{}
	mi := &file_warehouseGoodsService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseGoodsSelectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseGoodsSelectorResponse) ProtoMessage() {}

func (x *WarehouseGoodsSelectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warehouseGoodsService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseGoodsSelectorResponse.ProtoReflect.Descriptor instead.
func (*WarehouseGoodsSelectorResponse) Descriptor() ([]byte, []int) {
	return file_warehouseGoodsService_proto_rawDescGZIP(), []int{4}
}

func (x *WarehouseGoodsSelectorResponse) GetPager() *common.Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

func (x *WarehouseGoodsSelectorResponse) GetItems() []*Spu {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *WarehouseGoodsSelectorResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_warehouseGoodsService_proto protoreflect.FileDescriptor

const file_warehouseGoodsService_proto_rawDesc = "" +
	"\n" +
	"\x1bwarehouseGoodsService.proto\x12\bservices\x1a\x11common/base.proto\x1a\x15baseInfoService.proto\x1a\x10spuService.proto\x1a\x16warehouseService.proto\"\xe2\x02\n" +
	"\x0eWarehouseGoods\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x03R\vwarehouseId\x12\x15\n" +
	"\x06spu_id\x18\x03 \x01(\x03R\x05spuId\x12\x1c\n" +
	"\tinventory\x18\x04 \x01(\x03R\tinventory\x12\x1b\n" +
	"\tis_enable\x18\x05 \x01(\tR\bisEnable\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x121\n" +
	"\twarehouse\x18\t \x01(\v2\x13.services.WarehouseR\twarehouse\x12\x1f\n" +
	"\x03spu\x18\n" +
	" \x01(\v2\r.services.SpuR\x03spu\x129\n" +
	"\tspec_list\x18\v \x03(\v2\x1c.services.WarehouseGoodsSpecR\bspecList\"\xe9\x02\n" +
	"\x12WarehouseGoodsSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12,\n" +
	"\x12warehouse_goods_id\x18\x02 \x01(\x03R\x10warehouseGoodsId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\x03R\vwarehouseId\x12\x15\n" +
	"\x06spu_id\x18\x04 \x01(\x03R\x05spuId\x12\x16\n" +
	"\x06unique\x18\x05 \x01(\tR\x06unique\x12\x1c\n" +
	"\tinventory\x18\x06 \x01(\x03R\tinventory\x12)\n" +
	"\x04spec\x18\a \x03(\v2\x15.services.SkuSpecInfoR\x04spec\x12\x1b\n" +
	"\tspec_desc\x18\b \x01(\tR\bspecDesc\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\x03sku\x18\f \x01(\v2\r.services.SkuR\x03sku\"\xd1\x03\n" +
	"\x15WarehouseGoodsRequest\x12\x14\n" +
	"\x05paged\x18\x01 \x01(\x03R\x05paged\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\asorting\x18\x03 \x01(\tR\asorting\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\x12!\n" +
	"\fwarehouse_id\x18\x05 \x01(\x03R\vwarehouseId\x12\x15\n" +
	"\x06spu_id\x18\x06 \x01(\x03R\x05spuId\x12\x1c\n" +
	"\tinventory\x18\a \x01(\x03R\tinventory\x12\x1b\n" +
	"\tis_enable\x18\b \x01(\tR\bisEnable\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\x03R\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\n" +
	" \x01(\x05R\abrandId\x12\x17\n" +
	"\ashop_id\x18\v \x01(\x03R\x06shopId\x12\x19\n" +
	"\bgroup_id\x18\f \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12\x1a\n" +
	"\bkeywords\x18\x0e \x01(\tR\bkeywords\x12\x10\n" +
	"\x03ids\x18\x0f \x03(\x03R\x03ids\x12\x17\n" +
	"\aspu_ids\x18\x10 \x03(\x03R\x06spuIds\x12\x1b\n" +
	"\tgroup_ids\x18\x11 \x03(\x03R\bgroupIds\"\xb1\x01\n" +
	"\x16WarehouseGoodsResponse\x120\n" +
	"\x06entity\x18\x01 \x01(\v2\x18.services.WarehouseGoodsR\x06entity\x12#\n" +
	"\x05pager\x18\x02 \x01(\v2\r.common.PagerR\x05pager\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.services.WarehouseGoodsR\x05items\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\"|\n" +
	"\x1eWarehouseGoodsSelectorResponse\x12#\n" +
	"\x05pager\x18\x02 \x01(\v2\r.common.PagerR\x05pager\x12#\n" +
	"\x05items\x18\x03 \x03(\v2\r.services.SpuR\x05items\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg2\xb5\x04\n" +
	"\x15WarehouseGoodsService\x12F\n" +
	"\x06Create\x12\x18.services.WarehouseGoods\x1a .services.WarehouseGoodsResponse\"\x00\x12O\n" +
	"\x0fUpdateInventory\x12\x18.services.WarehouseGoods\x1a .services.WarehouseGoodsResponse\"\x00\x12F\n" +
	"\x06Delete\x12\x18.services.WarehouseGoods\x1a .services.WarehouseGoodsResponse\"\x00\x12F\n" +
	"\x06Detail\x12\x18.services.WarehouseGoods\x1a .services.WarehouseGoodsResponse\"\x00\x12K\n" +
	"\x04List\x12\x1f.services.WarehouseGoodsRequest\x1a .services.WarehouseGoodsResponse\"\x00\x12M\n" +
	"\x06Search\x12\x1f.services.WarehouseGoodsRequest\x1a .services.WarehouseGoodsResponse\"\x00\x12W\n" +
	"\bSelector\x12\x1f.services.WarehouseGoodsRequest\x1a(.services.WarehouseGoodsSelectorResponse\"\x00B\rZ\v/.;servicesb\x06proto3"

var (
	file_warehouseGoodsService_proto_rawDescOnce sync.Once
	file_warehouseGoodsService_proto_rawDescData []byte
)

func file_warehouseGoodsService_proto_rawDescGZIP() []byte {
	file_warehouseGoodsService_proto_rawDescOnce.Do(func() {
		file_warehouseGoodsService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warehouseGoodsService_proto_rawDesc), len(file_warehouseGoodsService_proto_rawDesc)))
	})
	return file_warehouseGoodsService_proto_rawDescData
}

var file_warehouseGoodsService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_warehouseGoodsService_proto_goTypes = []any{
	(*WarehouseGoods)(nil),                 // 0: services.WarehouseGoods
	(*WarehouseGoodsSpec)(nil),             // 1: services.WarehouseGoodsSpec
	(*WarehouseGoodsRequest)(nil),          // 2: services.WarehouseGoodsRequest
	(*WarehouseGoodsResponse)(nil),         // 3: services.WarehouseGoodsResponse
	(*WarehouseGoodsSelectorResponse)(nil), // 4: services.WarehouseGoodsSelectorResponse
	(*Warehouse)(nil),                      // 5: services.Warehouse
	(*Spu)(nil),                            // 6: services.Spu
	(*SkuSpecInfo)(nil),                    // 7: services.SkuSpecInfo
	(*Sku)(nil),                            // 8: services.Sku
	(*common.Pager)(nil),                   // 9: common.Pager
}
var file_warehouseGoodsService_proto_depIdxs = []int32{
	5,  // 0: services.WarehouseGoods.warehouse:type_name -> services.Warehouse
	6,  // 1: services.WarehouseGoods.spu:type_name -> services.Spu
	1,  // 2: services.WarehouseGoods.spec_list:type_name -> services.WarehouseGoodsSpec
	7,  // 3: services.WarehouseGoodsSpec.spec:type_name -> services.SkuSpecInfo
	8,  // 4: services.WarehouseGoodsSpec.sku:type_name -> services.Sku
	0,  // 5: services.WarehouseGoodsResponse.entity:type_name -> services.WarehouseGoods
	9,  // 6: services.WarehouseGoodsResponse.pager:type_name -> common.Pager
	0,  // 7: services.WarehouseGoodsResponse.items:type_name -> services.WarehouseGoods
	9,  // 8: services.WarehouseGoodsSelectorResponse.pager:type_name -> common.Pager
	6,  // 9: services.WarehouseGoodsSelectorResponse.items:type_name -> services.Spu
	0,  // 10: services.WarehouseGoodsService.Create:input_type -> services.WarehouseGoods
	0,  // 11: services.WarehouseGoodsService.UpdateInventory:input_type -> services.WarehouseGoods
	0,  // 12: services.WarehouseGoodsService.Delete:input_type -> services.WarehouseGoods
	0,  // 13: services.WarehouseGoodsService.Detail:input_type -> services.WarehouseGoods
	2,  // 14: services.WarehouseGoodsService.List:input_type -> services.WarehouseGoodsRequest
	2,  // 15: services.WarehouseGoodsService.Search:input_type -> services.WarehouseGoodsRequest
	2,  // 16: services.WarehouseGoodsService.Selector:input_type -> services.WarehouseGoodsRequest
	3,  // 17: services.WarehouseGoodsService.Create:output_type -> services.WarehouseGoodsResponse
	3,  // 18: services.WarehouseGoodsService.UpdateInventory:output_type -> services.WarehouseGoodsResponse
	3,  // 19: services.WarehouseGoodsService.Delete:output_type -> services.WarehouseGoodsResponse
	3,  // 20: services.WarehouseGoodsService.Detail:output_type -> services.WarehouseGoodsResponse
	3,  // 21: services.WarehouseGoodsService.List:output_type -> services.WarehouseGoodsResponse
	3,  // 22: services.WarehouseGoodsService.Search:output_type -> services.WarehouseGoodsResponse
	4,  // 23: services.WarehouseGoodsService.Selector:output_type -> services.WarehouseGoodsSelectorResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_warehouseGoodsService_proto_init() }
func file_warehouseGoodsService_proto_init() {
	if File_warehouseGoodsService_proto != nil {
		return
	}
	file_baseInfoService_proto_init()
	file_spuService_proto_init()
	file_warehouseService_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warehouseGoodsService_proto_rawDesc), len(file_warehouseGoodsService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warehouseGoodsService_proto_goTypes,
		DependencyIndexes: file_warehouseGoodsService_proto_depIdxs,
		MessageInfos:      file_warehouseGoodsService_proto_msgTypes,
	}.Build()
	File_warehouseGoodsService_proto = out.File
	file_warehouseGoodsService_proto_goTypes = nil
	file_warehouseGoodsService_proto_depIdxs = nil
}
