// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: stockWarnService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StockWarnService service

func NewStockWarnServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StockWarnService service

type StockWarnService interface {
	Set(ctx context.Context, in *StockWarn, opts ...client.CallOption) (*StockWarnResponse, error)
	Get(ctx context.Context, in *StockWarn, opts ...client.CallOption) (*StockWarnResponse, error)
	List(ctx context.Context, in *StockWarnRequest, opts ...client.CallOption) (*StockWarnResponse, error)
	Search(ctx context.Context, in *StockWarnRequest, opts ...client.CallOption) (*StockWarnResponse, error)
}

type stockWarnService struct {
	c    client.Client
	name string
}

func NewStockWarnService(name string, c client.Client) StockWarnService {
	return &stockWarnService{
		c:    c,
		name: name,
	}
}

func (c *stockWarnService) Set(ctx context.Context, in *StockWarn, opts ...client.CallOption) (*StockWarnResponse, error) {
	req := c.c.NewRequest(c.name, "StockWarnService.Set", in)
	out := new(StockWarnResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockWarnService) Get(ctx context.Context, in *StockWarn, opts ...client.CallOption) (*StockWarnResponse, error) {
	req := c.c.NewRequest(c.name, "StockWarnService.Get", in)
	out := new(StockWarnResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockWarnService) List(ctx context.Context, in *StockWarnRequest, opts ...client.CallOption) (*StockWarnResponse, error) {
	req := c.c.NewRequest(c.name, "StockWarnService.List", in)
	out := new(StockWarnResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockWarnService) Search(ctx context.Context, in *StockWarnRequest, opts ...client.CallOption) (*StockWarnResponse, error) {
	req := c.c.NewRequest(c.name, "StockWarnService.Search", in)
	out := new(StockWarnResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StockWarnService service

type StockWarnServiceHandler interface {
	Set(context.Context, *StockWarn, *StockWarnResponse) error
	Get(context.Context, *StockWarn, *StockWarnResponse) error
	List(context.Context, *StockWarnRequest, *StockWarnResponse) error
	Search(context.Context, *StockWarnRequest, *StockWarnResponse) error
}

func RegisterStockWarnServiceHandler(s server.Server, hdlr StockWarnServiceHandler, opts ...server.HandlerOption) error {
	type stockWarnService interface {
		Set(ctx context.Context, in *StockWarn, out *StockWarnResponse) error
		Get(ctx context.Context, in *StockWarn, out *StockWarnResponse) error
		List(ctx context.Context, in *StockWarnRequest, out *StockWarnResponse) error
		Search(ctx context.Context, in *StockWarnRequest, out *StockWarnResponse) error
	}
	type StockWarnService struct {
		stockWarnService
	}
	h := &stockWarnServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StockWarnService{h}, opts...))
}

type stockWarnServiceHandler struct {
	StockWarnServiceHandler
}

func (h *stockWarnServiceHandler) Set(ctx context.Context, in *StockWarn, out *StockWarnResponse) error {
	return h.StockWarnServiceHandler.Set(ctx, in, out)
}

func (h *stockWarnServiceHandler) Get(ctx context.Context, in *StockWarn, out *StockWarnResponse) error {
	return h.StockWarnServiceHandler.Get(ctx, in, out)
}

func (h *stockWarnServiceHandler) List(ctx context.Context, in *StockWarnRequest, out *StockWarnResponse) error {
	return h.StockWarnServiceHandler.List(ctx, in, out)
}

func (h *stockWarnServiceHandler) Search(ctx context.Context, in *StockWarnRequest, out *StockWarnResponse) error {
	return h.StockWarnServiceHandler.Search(ctx, in, out)
}
