// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: expressConfigService.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 快递发货配置
type ExpressConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomName            string `protobuf:"bytes,1,opt,name=customName,proto3" json:"customName"`                        //自定义名称
	IsDefault             bool   `protobuf:"varint,3,opt,name=isDefault,proto3" json:"isDefault"`                         //设置为默认配送方式
	FreightConstituteRule int32  `protobuf:"varint,4,opt,name=freightConstituteRule,proto3" json:"freightConstituteRule"` //计费方式:1-累加运费,2-组合运费
}

func (x *ExpressConfig) Reset() {
	*x = ExpressConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expressConfigService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressConfig) ProtoMessage() {}

func (x *ExpressConfig) ProtoReflect() protoreflect.Message {
	mi := &file_expressConfigService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressConfig.ProtoReflect.Descriptor instead.
func (*ExpressConfig) Descriptor() ([]byte, []int) {
	return file_expressConfigService_proto_rawDescGZIP(), []int{0}
}

func (x *ExpressConfig) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

func (x *ExpressConfig) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ExpressConfig) GetFreightConstituteRule() int32 {
	if x != nil {
		return x.FreightConstituteRule
	}
	return 0
}

var File_expressConfigService_proto protoreflect.FileDescriptor

var file_expressConfigService_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x15, 0x66, 0x72, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x66, 0x72, 0x65, 0x69, 0x67, 0x68, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x42, 0x0d, 0x5a, 0x0b,
	0x2f, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_expressConfigService_proto_rawDescOnce sync.Once
	file_expressConfigService_proto_rawDescData = file_expressConfigService_proto_rawDesc
)

func file_expressConfigService_proto_rawDescGZIP() []byte {
	file_expressConfigService_proto_rawDescOnce.Do(func() {
		file_expressConfigService_proto_rawDescData = protoimpl.X.CompressGZIP(file_expressConfigService_proto_rawDescData)
	})
	return file_expressConfigService_proto_rawDescData
}

var file_expressConfigService_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_expressConfigService_proto_goTypes = []interface{}{
	(*ExpressConfig)(nil), // 0: services.ExpressConfig
}
var file_expressConfigService_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_expressConfigService_proto_init() }
func file_expressConfigService_proto_init() {
	if File_expressConfigService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expressConfigService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expressConfigService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expressConfigService_proto_goTypes,
		DependencyIndexes: file_expressConfigService_proto_depIdxs,
		MessageInfos:      file_expressConfigService_proto_msgTypes,
	}.Build()
	File_expressConfigService_proto = out.File
	file_expressConfigService_proto_rawDesc = nil
	file_expressConfigService_proto_goTypes = nil
	file_expressConfigService_proto_depIdxs = nil
}
