// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: localProviderService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LocalProviderService service

func NewLocalProviderServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LocalProviderService service

type LocalProviderService interface {
	// 同城配送服务商新增
	Create(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error)
	// 同城配送服务商修改
	Update(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error)
	// 同城配送服务商删除
	Delete(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error)
	// 同城配送服务商获取
	Get(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error)
	// 同城配送服务商查询
	Search(ctx context.Context, in *LocalProviderRequest, opts ...client.CallOption) (*LocalProviderResponse, error)
	// 同城配送服务商列表
	List(ctx context.Context, in *LocalProviderRequest, opts ...client.CallOption) (*LocalProviderResponse, error)
}

type localProviderService struct {
	c    client.Client
	name string
}

func NewLocalProviderService(name string, c client.Client) LocalProviderService {
	return &localProviderService{
		c:    c,
		name: name,
	}
}

func (c *localProviderService) Create(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error) {
	req := c.c.NewRequest(c.name, "LocalProviderService.Create", in)
	out := new(LocalProviderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localProviderService) Update(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error) {
	req := c.c.NewRequest(c.name, "LocalProviderService.Update", in)
	out := new(LocalProviderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localProviderService) Delete(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error) {
	req := c.c.NewRequest(c.name, "LocalProviderService.Delete", in)
	out := new(LocalProviderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localProviderService) Get(ctx context.Context, in *LocalProvider, opts ...client.CallOption) (*LocalProviderResponse, error) {
	req := c.c.NewRequest(c.name, "LocalProviderService.Get", in)
	out := new(LocalProviderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localProviderService) Search(ctx context.Context, in *LocalProviderRequest, opts ...client.CallOption) (*LocalProviderResponse, error) {
	req := c.c.NewRequest(c.name, "LocalProviderService.Search", in)
	out := new(LocalProviderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localProviderService) List(ctx context.Context, in *LocalProviderRequest, opts ...client.CallOption) (*LocalProviderResponse, error) {
	req := c.c.NewRequest(c.name, "LocalProviderService.List", in)
	out := new(LocalProviderResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LocalProviderService service

type LocalProviderServiceHandler interface {
	// 同城配送服务商新增
	Create(context.Context, *LocalProvider, *LocalProviderResponse) error
	// 同城配送服务商修改
	Update(context.Context, *LocalProvider, *LocalProviderResponse) error
	// 同城配送服务商删除
	Delete(context.Context, *LocalProvider, *LocalProviderResponse) error
	// 同城配送服务商获取
	Get(context.Context, *LocalProvider, *LocalProviderResponse) error
	// 同城配送服务商查询
	Search(context.Context, *LocalProviderRequest, *LocalProviderResponse) error
	// 同城配送服务商列表
	List(context.Context, *LocalProviderRequest, *LocalProviderResponse) error
}

func RegisterLocalProviderServiceHandler(s server.Server, hdlr LocalProviderServiceHandler, opts ...server.HandlerOption) error {
	type localProviderService interface {
		Create(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error
		Update(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error
		Delete(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error
		Get(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error
		Search(ctx context.Context, in *LocalProviderRequest, out *LocalProviderResponse) error
		List(ctx context.Context, in *LocalProviderRequest, out *LocalProviderResponse) error
	}
	type LocalProviderService struct {
		localProviderService
	}
	h := &localProviderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LocalProviderService{h}, opts...))
}

type localProviderServiceHandler struct {
	LocalProviderServiceHandler
}

func (h *localProviderServiceHandler) Create(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error {
	return h.LocalProviderServiceHandler.Create(ctx, in, out)
}

func (h *localProviderServiceHandler) Update(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error {
	return h.LocalProviderServiceHandler.Update(ctx, in, out)
}

func (h *localProviderServiceHandler) Delete(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error {
	return h.LocalProviderServiceHandler.Delete(ctx, in, out)
}

func (h *localProviderServiceHandler) Get(ctx context.Context, in *LocalProvider, out *LocalProviderResponse) error {
	return h.LocalProviderServiceHandler.Get(ctx, in, out)
}

func (h *localProviderServiceHandler) Search(ctx context.Context, in *LocalProviderRequest, out *LocalProviderResponse) error {
	return h.LocalProviderServiceHandler.Search(ctx, in, out)
}

func (h *localProviderServiceHandler) List(ctx context.Context, in *LocalProviderRequest, out *LocalProviderResponse) error {
	return h.LocalProviderServiceHandler.List(ctx, in, out)
}
