// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: memberVipService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MemberVipService service

func NewMemberVipServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MemberVipService service

type MemberVipService interface {
	//会员中心
	Index(ctx context.Context, in *MemberVip, opts ...client.CallOption) (*MemberVipIndexResponse, error)
	//分享海报
	Poster(ctx context.Context, in *MemberVip, opts ...client.CallOption) (*MemberVipPosterResponse, error)
	Get(ctx context.Context, in *MemberVip, opts ...client.CallOption) (*MemberVipResponse, error)
	Search(ctx context.Context, in *MemberVipRequest, opts ...client.CallOption) (*MemberVipResponse, error)
	List(ctx context.Context, in *MemberVipRequest, opts ...client.CallOption) (*MemberVipResponse, error)
}

type memberVipService struct {
	c    client.Client
	name string
}

func NewMemberVipService(name string, c client.Client) MemberVipService {
	return &memberVipService{
		c:    c,
		name: name,
	}
}

func (c *memberVipService) Index(ctx context.Context, in *MemberVip, opts ...client.CallOption) (*MemberVipIndexResponse, error) {
	req := c.c.NewRequest(c.name, "MemberVipService.Index", in)
	out := new(MemberVipIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberVipService) Poster(ctx context.Context, in *MemberVip, opts ...client.CallOption) (*MemberVipPosterResponse, error) {
	req := c.c.NewRequest(c.name, "MemberVipService.Poster", in)
	out := new(MemberVipPosterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberVipService) Get(ctx context.Context, in *MemberVip, opts ...client.CallOption) (*MemberVipResponse, error) {
	req := c.c.NewRequest(c.name, "MemberVipService.Get", in)
	out := new(MemberVipResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberVipService) Search(ctx context.Context, in *MemberVipRequest, opts ...client.CallOption) (*MemberVipResponse, error) {
	req := c.c.NewRequest(c.name, "MemberVipService.Search", in)
	out := new(MemberVipResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberVipService) List(ctx context.Context, in *MemberVipRequest, opts ...client.CallOption) (*MemberVipResponse, error) {
	req := c.c.NewRequest(c.name, "MemberVipService.List", in)
	out := new(MemberVipResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MemberVipService service

type MemberVipServiceHandler interface {
	//会员中心
	Index(context.Context, *MemberVip, *MemberVipIndexResponse) error
	//分享海报
	Poster(context.Context, *MemberVip, *MemberVipPosterResponse) error
	Get(context.Context, *MemberVip, *MemberVipResponse) error
	Search(context.Context, *MemberVipRequest, *MemberVipResponse) error
	List(context.Context, *MemberVipRequest, *MemberVipResponse) error
}

func RegisterMemberVipServiceHandler(s server.Server, hdlr MemberVipServiceHandler, opts ...server.HandlerOption) error {
	type memberVipService interface {
		Index(ctx context.Context, in *MemberVip, out *MemberVipIndexResponse) error
		Poster(ctx context.Context, in *MemberVip, out *MemberVipPosterResponse) error
		Get(ctx context.Context, in *MemberVip, out *MemberVipResponse) error
		Search(ctx context.Context, in *MemberVipRequest, out *MemberVipResponse) error
		List(ctx context.Context, in *MemberVipRequest, out *MemberVipResponse) error
	}
	type MemberVipService struct {
		memberVipService
	}
	h := &memberVipServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MemberVipService{h}, opts...))
}

type memberVipServiceHandler struct {
	MemberVipServiceHandler
}

func (h *memberVipServiceHandler) Index(ctx context.Context, in *MemberVip, out *MemberVipIndexResponse) error {
	return h.MemberVipServiceHandler.Index(ctx, in, out)
}

func (h *memberVipServiceHandler) Poster(ctx context.Context, in *MemberVip, out *MemberVipPosterResponse) error {
	return h.MemberVipServiceHandler.Poster(ctx, in, out)
}

func (h *memberVipServiceHandler) Get(ctx context.Context, in *MemberVip, out *MemberVipResponse) error {
	return h.MemberVipServiceHandler.Get(ctx, in, out)
}

func (h *memberVipServiceHandler) Search(ctx context.Context, in *MemberVipRequest, out *MemberVipResponse) error {
	return h.MemberVipServiceHandler.Search(ctx, in, out)
}

func (h *memberVipServiceHandler) List(ctx context.Context, in *MemberVipRequest, out *MemberVipResponse) error {
	return h.MemberVipServiceHandler.List(ctx, in, out)
}
