// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: downloadService.proto

package services

import (
	fmt "fmt"
	_ "github.com/geiqin/micro-kit/protobuf/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DownloadService service

func NewDownloadServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for DownloadService service

type DownloadService interface {
	//生成下载文件开始
	BuildBegin(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error)
	//生成下载文件结束
	BuildEnd(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error)
	//创建下载信息
	Create(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error)
	//修改下载信息
	Update(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error)
	//删除下载信息
	Delete(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error)
	//获得下载信息
	Get(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error)
	//生成下载地址
	MakeUrl(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadUrlResponse, error)
	//查询下载信息
	Search(ctx context.Context, in *DownloadRequest, opts ...client.CallOption) (*DownloadResponse, error)
}

type downloadService struct {
	c    client.Client
	name string
}

func NewDownloadService(name string, c client.Client) DownloadService {
	return &downloadService{
		c:    c,
		name: name,
	}
}

func (c *downloadService) BuildBegin(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.BuildBegin", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) BuildEnd(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.BuildEnd", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) Create(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.Create", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) Update(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.Update", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) Delete(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.Delete", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) Get(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.Get", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) MakeUrl(ctx context.Context, in *Download, opts ...client.CallOption) (*DownloadUrlResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.MakeUrl", in)
	out := new(DownloadUrlResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadService) Search(ctx context.Context, in *DownloadRequest, opts ...client.CallOption) (*DownloadResponse, error) {
	req := c.c.NewRequest(c.name, "DownloadService.Search", in)
	out := new(DownloadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DownloadService service

type DownloadServiceHandler interface {
	//生成下载文件开始
	BuildBegin(context.Context, *Download, *DownloadResponse) error
	//生成下载文件结束
	BuildEnd(context.Context, *Download, *DownloadResponse) error
	//创建下载信息
	Create(context.Context, *Download, *DownloadResponse) error
	//修改下载信息
	Update(context.Context, *Download, *DownloadResponse) error
	//删除下载信息
	Delete(context.Context, *Download, *DownloadResponse) error
	//获得下载信息
	Get(context.Context, *Download, *DownloadResponse) error
	//生成下载地址
	MakeUrl(context.Context, *Download, *DownloadUrlResponse) error
	//查询下载信息
	Search(context.Context, *DownloadRequest, *DownloadResponse) error
}

func RegisterDownloadServiceHandler(s server.Server, hdlr DownloadServiceHandler, opts ...server.HandlerOption) error {
	type downloadService interface {
		BuildBegin(ctx context.Context, in *Download, out *DownloadResponse) error
		BuildEnd(ctx context.Context, in *Download, out *DownloadResponse) error
		Create(ctx context.Context, in *Download, out *DownloadResponse) error
		Update(ctx context.Context, in *Download, out *DownloadResponse) error
		Delete(ctx context.Context, in *Download, out *DownloadResponse) error
		Get(ctx context.Context, in *Download, out *DownloadResponse) error
		MakeUrl(ctx context.Context, in *Download, out *DownloadUrlResponse) error
		Search(ctx context.Context, in *DownloadRequest, out *DownloadResponse) error
	}
	type DownloadService struct {
		downloadService
	}
	h := &downloadServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DownloadService{h}, opts...))
}

type downloadServiceHandler struct {
	DownloadServiceHandler
}

func (h *downloadServiceHandler) BuildBegin(ctx context.Context, in *Download, out *DownloadResponse) error {
	return h.DownloadServiceHandler.BuildBegin(ctx, in, out)
}

func (h *downloadServiceHandler) BuildEnd(ctx context.Context, in *Download, out *DownloadResponse) error {
	return h.DownloadServiceHandler.BuildEnd(ctx, in, out)
}

func (h *downloadServiceHandler) Create(ctx context.Context, in *Download, out *DownloadResponse) error {
	return h.DownloadServiceHandler.Create(ctx, in, out)
}

func (h *downloadServiceHandler) Update(ctx context.Context, in *Download, out *DownloadResponse) error {
	return h.DownloadServiceHandler.Update(ctx, in, out)
}

func (h *downloadServiceHandler) Delete(ctx context.Context, in *Download, out *DownloadResponse) error {
	return h.DownloadServiceHandler.Delete(ctx, in, out)
}

func (h *downloadServiceHandler) Get(ctx context.Context, in *Download, out *DownloadResponse) error {
	return h.DownloadServiceHandler.Get(ctx, in, out)
}

func (h *downloadServiceHandler) MakeUrl(ctx context.Context, in *Download, out *DownloadUrlResponse) error {
	return h.DownloadServiceHandler.MakeUrl(ctx, in, out)
}

func (h *downloadServiceHandler) Search(ctx context.Context, in *DownloadRequest, out *DownloadResponse) error {
	return h.DownloadServiceHandler.Search(ctx, in, out)
}
